version: "3"

services:
  api:
    build: 
      context: ./.docker
      dockerfile: Dockerfile
    ports: ["3000:3000"]
    working_dir: /usr/src/app
    volumes: 
      - ./:/usr/src/app
    command: npm run dev
    tty: true
    environment: 
      - GOOGLE_CLOUD_PROJECT=
      - GOOGLE_APPLICATION_CREDENTIALS=

  mysql:
    image: mariadb
    ports: ["3306:3306"]
    environment:
        MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./mysql:/var/lib/mysql